### ISSUE TITLE
Re: 'Companies House'

### ISSUE THREAD

**Issue by DevelopmentDan** [co-cddo/api-catalogue#333]
Problem with 'Companies House' (https://www.api.gov.uk/ch/companies-house/)
GET https://api.company-information.service.gov.uk/advanced-search/companies
the company_name parameter is completely ignored in the search. 

(As documented here: https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/reference/search/advanced-company-search)

https://api.company-information.service.gov.uk/advanced-search/companies?start_index=1&company_name=mortgage&sic_codes=66190&incorporated_from=2022-01-01&size=200&company_status=active

brings back exactly the same list as:

https://api.company-information.service.gov.uk/advanced-search/companies?start_index=1&sic_codes=66190&incorporated_from=2022-01-01&size=200&company_status=active

**Comment by jamietanna** [comment]
Thanks for reaching out!

The owners of this repo (CDDO) don't actually maintain the APIs listed within it. On https://www.api.gov.uk/ch/companies-house/, the [linked documentation site](https://developer.company-information.service.gov.uk/) has a contact page that you can use to reach out to the maintainers of the API :+1:

**Comment by DevelopmentDan** [comment]
> Thanks for reaching out!
> 
> The owners of this repo (CDDO) don't actually maintain the APIs listed within it. On https://www.api.gov.uk/ch/companies-house/, the [linked documentation site](https://developer.company-information.service.gov.uk/) has a contact page that you can use to reach out to the maintainers of the API 👍

This page: https://www.api.gov.uk/ch/companies-house/#companies-house needs the "report a problem" link removing then because it is pointless.

**Comment by jamietanna** [comment]
Thanks Dan, we're currently working through User Research to refine the catalogue, and one of the actions we've got is to clarify that the catalogue isn't owned by development/support teams, as well as the fact that "report a problem" is about the page you're on, rather than the API itself

**Comment by DevelopmentDan** [comment]
Thank you. I've reported the bug to companies house. Hopefully they will fix it soon.
