### ISSUE TITLE
Re: 'GOV.UK Trade Tariff API'

### ISSUE THREAD

**Issue by mattlavis-transform** [co-cddo/api-catalogue#397]
Problem with 'GOV.UK Trade Tariff API' (https://www.api.gov.uk/hmrc/gov-uk-trade-tariff-api/)

Hi there. Not a problem as such, but just a request to change the presented email address for the support team. The supporting agency enginegroup has been renamed as transform, which has the domain transformuk.

Please could I request that the support email address be renamed as:

trade-tariff-support@transformuk.com

BTW - I am the technical product owner for the service.

Thanks very much
Matt Lavis (matt.lavis@digital.hmrc.gov.uk)

**Comment by nahteb** [comment]
Hi Matt, thanks for raising, this has been updated now
