### ISSUE TITLE
Email api-catalogue@digital.cabinet-office.gov.uk does not seem monitored

### ISSUE THREAD

**Issue by johnnybaloney** [co-cddo/api-catalogue#481]
The email address from the readme [api-catalogue@digital.cabinet-office.gov.uk](mailto:api-catalogue@digital.cabinet-office.gov.uk) does not seem to be monitored. I sent a query on the 15th of September and haven't received any reply.

Please update the address if incorrect or add what sort of timeframe for responses to expect.

**Comment by charlesbaird-dsa** [comment]
Sorry for the delayed response - we're a small team that just manages the catalogue and doesn't have visibility over APIs from across the whole of government, but does get a lot of requests!
