### ISSUE TITLE
GOV.UK PaaS catalogue entry

### ISSUE THREAD

**Issue by pauldougan** [co-cddo/api-catalogue#506]
Problem with 'GOV.UK PaaS v3' (https://www.api.gov.uk/gds/gov-uk-paas-v3/)

in the light of the GDS decision to [decommission GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) we would like to remove the entries in the api catalogue that refer to the service as a whole. Although the intention is to maintain the service til the end of 2023 we probably don't want  anyone to start building against the api given the plan.

How best to make the change to the repo, I'm part of GDS and don't have rights to this repo to make a pull request

**Comment by pauldougan** [comment]
fyi I mentioned this in passing to @charlesbaird-dsa

**Comment by charlesbaird-dsa** [comment]
Hi Paul - do you want to remove the whole entry, or make changes to it to reflect the decommissioning? If the latter, let us have the changed text in here and we'll get it updated.

**Comment by AP-Hunt** [comment]
I would suggest simply removing the whole entry. We won't be maintaining an archive or a read-only version of anything, so it seems slightly pointless to list it.

**Comment by pauldougan** [comment]
hi, any advice on how to remove the paas entries from the catalog. the service is due to wind down on dec 23 so the entry is redundant

**Comment by kr8n3r** [comment]
any update on removing this?

**Comment by pauldougan** [comment]
@kr8n3r don't think so, I am going to fork this repo and make the change to remove all mention of GOV.UK PaaS http://cloud.service.gov.uk then submit a pr to this upstream repository. Given the platform is decommissioned from mainstream service it makes sense to remove this. 

![image](https://github.com/co-cddo/api-catalogue/assets/34273121/db498c5f-3efe-48f5-a334-f1bd07f3f10d)

**Comment by pauldougan** [comment]
ok I submitted PR #765 to merge a change removing the paas rows from the catalogue csv file
