### ISSUE TITLE
HM Land Registry: e-Document Registration Service

### ISSUE THREAD

**Issue by SPD-LR** [co-cddo/api-catalogue#518]
**Please fill in the following information:**

**Base URL: https://businessgateway.landregistry.gov.uk/b2b/ECDRS_SoapEngine/EDocumentRegistrationV2_1WebService?wsdl**
The URL for the API. For example, `https://www.gov.uk/api/content`. Please limit this to one URL - if you have sandbox environments or multiple endpoints please add them to the description.

**Name: e-Document Registration Service**
The name of the API. For example, `Gov.uk Content`.

**Description: 
Overview

Use this service to:

 - send applications to change the register
 - automate the collection of correspondence and responses
 - receive the completed application back

If you’re a software developer:

- Use this document to integrate data into your system

Poll Request Service URL for production environment: https://businessgateway.landregistry.gov.uk/b2b/ECDRS_SoapEngine/EDocumentRegistrationV2_1PollRequestWebService?wsdl

Attachment Service URLs:
https://businessgateway.landregistry.gov.uk/b2b/ECDRS_SoapEngine/AttachmentV2_1WebService?wsdl
https://businessgateway.landregistry.gov.uk/b2b/ECDRS_SoapEngine/AttachmentV2_1PollRequestWebService?wsdl

Correspondence/Requisition URL:
https://businessgateway.landregistry.gov.uk/b2b/ECDRS_SoapEngine/CorrespondenceV2_1PollRequestWebService?wsdl

Early Completion URL:
https://businessgateway.landregistry.gov.uk/b2b/ECDRS_SoapEngine/EarlyCompletionV2_1PollRequestWebService?wsdl

For test environment endpoints, replace https://businessgateway.landregistry.gov.uk/b2b/ECDRS_SoapEngine with https://bgtest.landregistry.gov.uk/b2b/ECDRS_StubService**

The description of what the API is about. Please make this as detailed as possible to help users search. For example "GOV.UK Content API makes it easy to access the data used to render content on https://www.gov.uk. For any page hosted on GOV.UK you can use the path to access the content and associated metadata for a page."

**Documentation URL: https://landregistry.github.io/bgtechdoc/services/edrs/**
The URL for the API documentation. For example `https://content-api.publishing.service.gov.uk/`

**Maintainer: channelpartners@landregistry.gov.uk**
Contact details for the team who manage the API, and who will be the first point of contact for a user wishing to access the service. Please don't use an individual's email address.

**Provider: HM Land Registry**
The full name of the department or organisation who provide the API. For example 'Government Digital Service'.

**Area Served:**
Optional - The geographic area that the API serves. For example: 'Greater London'.

**Start Date:**
Optional - The date the API comes into service. For example: '2020-07-01'.

**End Date:**
Optional - The date the API will be retired. For example: '2022-07-01'.

**Alternate Name:**
Optional - the acronym of the department or organisation. For example: 'GDS'.

**Provider URL:**
Optional - the canonical URL of the website of the department or organisation. For example: 'https://www.gov.uk/government/organisations/government-digital-service'.

If you have multiple APIs to add, you can use a CSV template with these fields which is available at: https://raw.githubusercontent.com/co-cddo/api-catalogue/HEAD/data/apic-csvtemplate.csv

Optionally, if you have more information you want to share with the API Catalogue community, please add it below.

**Comment by SPD-LR** [comment]
Hi all, I'm wondering if there's an error or omission in my submission which is preventing the publication of the entry into the catalogue?

Many thanks,

Simon.

**Comment by SPD-LR** [comment]
Hi Bethan,

Thanks for your response. Great to see the listing is live.

There does appear to be an error in the listing however:

***@***.***

The highlighted line above duplicates the bulleted line above it.

My request:

***@***.***

If this could be amended, I'd be grateful.

Kind regards,

Simon.

Simon Devey
Pre-Integration Support Manager
Customer & Strategy Directorate

Land Registry Telford Office, Parkside Court, Hall Park Way, Telford TF3 4LR.
GOV.UK<https://www.gov.uk/land-registry> | @HMLandRegistry<https://twitter.com/HMLandRegistry> | LinkedIn<http://www.linkedin.com/company/land-registry> | Facebook<https://www.facebook.com/hmlandregistry>
Email: ***@***.******@***.***>

**Comment by nahteb** [comment]
hi Simon, thanks for letting us know, this should be fixed now
