### ISSUE TITLE
Re: 'Local Land Charges Search'

### ISSUE THREAD

**Issue by SPD-LR** [co-cddo/api-catalogue#595]
Problem with 'Local Land Charges Search' (https://www.api.gov.uk/hmlr/local-land-charges-search/)

Can the two asterisks please be removed from this line:

https://bgtest.landregistry.gov.uk/b2b/ECLLC_StubService**

Many thanks,

Simon.

**Comment by SPD-LR** [comment]
Hi, can this please be bumped up please?

**Comment by RobNicholsGDS** [comment]
A fix has been has been merged. @SPD-LR Could you please check the entry to make sure you are happy with the fix.

**Comment by SPD-LR** [comment]
Hi Rob,

That's great, much appreciated.

Simon.
