### ISSUE TITLE
Re: 'Bank Holidays'

### ISSUE THREAD

**Issue by AntonZogk** [co-cddo/api-catalogue#626]
Problem with 'Bank Holidays' (https://www.api.gov.uk/gds/bank-holidays/) 

When loading the bank holidays in R there is typo  "New Yearâ€™s Day", it is not an issue at all :), but i thought i should let you know about this.

**Comment by nahteb** [comment]
Hi Anton, thanks for raising this issue - this catalogue just documents details about the APIs and we don't have sight of the APIs themselves so unfortunately I can't help with this.
