### ISSUE TITLE
Department for Education/Eligibility Checking System (ECS)

### ISSUE THREAD

**Issue by martin-hamilton** [co-cddo/api-catalogue#656]
**Base URL:**
N/A - API details are only made available on application by local authorities

**Name:**
Eligibility Checking System (ECS)

**Description:**
The Department for Education (DfE) provides an Eligibility Checking System (ECS) to allow local authorities to check online and in real time the eligibility status of parents/carers as part of an application for several types of passported benefits including Free School Meals (FSM) for their children, Funded Early Education for 2 Year Olds (EY) and to support local authorities to establish early years pupil premium (EYPP) funding for service providers. The ECS also provides checking to allow local authorities to verify online and in real time the validity of eligibility codes issued by HMRC to working parents eligible for 30 Hours Free Childcare.

**Documentation URL:**
N/A - API details are only made available on application by local authorities

**Maintainer:**
If you are a Local Authority user of the ECS and require assistance, or to sign up for access to the API, please email the [DfE ECS Service Desk](mailto:ECS.ADMIN@education.gov.uk)

**Provider:**
Department for Education

**Area Served:**
England and Wales:
- Free school meals
England only:
- Funded early learning for two year olds
- Early Years Pupil Premium
- 30 Hours Free Childcare

**Alternate Name:**
DfE

**Provider URL:**
https://www.gov.uk/government/organisations/department-for-education

**Comment by martin-hamilton** [comment]
FYI - I'm not involved in any way with this, just using it for a project

**Comment by RobNicholsGDS** [comment]
Thank you for this, but the API would only be registered on the site if the owners requested it.
