### ISSUE TITLE
UK Api

### ISSUE THREAD

**Issue by MdIbrahimBashar11** [co-cddo/api-catalogue#679]
**Describe the bug**

**Remember that we only control the API Catalogue - so bugs reported should be for that product only. For issues with specific APIs, please use the contact details on the listing of that API.**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RobNicholsGDS** [comment]
No problem described - please re-open with a description of the issue if necessary
