### ISSUE TITLE
Re: 'Bank Holidays'

### ISSUE THREAD

**Issue by narendra-tangudu** [co-cddo/api-catalogue#699]
Problem with 'Bank Holidays' (https://www.api.gov.uk/gds/bank-holidays/):

Unable to access this API using nodejs fetch method. Getting this below issue: 
err":{"type":"FetchError","message":"request to https://www.gov.uk/bank-holidays.json failed, reason: unable to get local issuer certificate","stack":"FetchError: request to https://www.gov.uk/bank-holidays.json failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (/opt/app/node_modules/node-fetch/lib/index.js:1505:11)\n    at ClientRequest.emit (node:events:511:28)\n    at TLSSocket.socketErrorListener (node:_http_client:495:9)\n    at TLSSocket.emit (node:events:511:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","errno":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY","code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY","name":"FetchError"},"message":"request to https://www.gov.uk/bank-holidays.json failed, reason: unable to get local issuer certificate"

**Comment by RobNicholsGDS** [comment]
Hi. I am afraid this is the repository for the API Register and is the place to report bugs with the Register and not the individual APIs registered.

The app that provides the API endpoint that you are having a problem with has its own Github Repo. Can you please submit your issue there: https://github.com/alphagov/calendars/issues
