### ISSUE TITLE
Re: 'Ministry of Justice' - API list

### ISSUE THREAD

**Issue by luke-a-williams** [co-cddo/api-catalogue#707]
Problem with 'Ministry of Justice' (https://www.api.gov.uk/moj/)
This Alpha page only lists 4 APIs, only 1 of which has associated Swagger specs to consume.
However the following page: https://structurizr.com/share/56937/documentation#published-apis
Lists 25 published APIs within the MoJ space. Should this be updated and any difference reflected in one central point of truth?

**Comment by RobNicholsGDS** [comment]
I am afraid we just maintain the catalogue. If you have a problem with the service provided by the Ministry of Justice, you will need to contact them with your suggested fix.
