### ISSUE TITLE
Re: 'Document Checking Service pilot'

### ISSUE THREAD

**Issue by BreninSul** [co-cddo/api-catalogue#713]
Problem with 'Document Checking Service pilot' (https://www.api.gov.uk/gds/document-checking-service-pilot/)
Link https://dcs-pilot-docs.cloudapps.digital/#the-document-checking-service-pilot is broken

`404
Not Found

Requested route ('dcs-pilot-docs.cloudapps.digital') does not exist.

unknown_route`

<img width="882" alt="зображення" src="https://github.com/co-cddo/api-catalogue/assets/42633769/553c9b08-e08c-49ec-9b01-aa8d2964779d">

**Comment by BreninSul** [comment]
It seems that Document Checking Service pilot ended on 31 March 2022..
But API page information hsve to be updated

https://www.gov.uk/government/collections/document-checking-service-pilot

**Comment by RobNicholsGDS** [comment]
Thank you @BreninSul. The record has been removed from the catalogue.
