### ISSUE TITLE
Re: 'UK Global Tariff (measures on declarable commodities)'

### ISSUE THREAD

**Issue by CRISDANTE** [co-cddo/api-catalogue#732]
Problem with 'UK Global Tariff (measures on declarable commodities)' (https://www.api.gov.uk/dit/uk-global-tariff-measures-on-declarable-commodities/)

Some data's are misaligned. how to correct and to use in power query

**Comment by RobNicholsGDS** [comment]
I am afraid we just maintain the catalogue and not the services listed within it.

You will need to contact the Department for International Trade if there is a problem with the data they are providing.
