### ISSUE TITLE
Does a Job Search API exist?

### ISSUE THREAD

**Issue by arhussain1** [co-cddo/api-catalogue#745]
Hi 

I am looking to create a job hunting application, I wanted to know if the uk gov has a job search api for vacancies listed on both:
- https://www.civilservicejobs.service.gov.uk/csr/index.cgi
- https://www.gov.uk/find-a-job

**Comment by RobNicholsGDS** [comment]
I am afraid we just provide the catalogue platform. If the API you are seeking is not listed in the catalogue you will need to contact the departments owning that data to enquire about whether there is an API available.
