### ISSUE TITLE
Re: 'Bank Holidays'

### ISSUE THREAD

**Issue by jchristo22** [co-cddo/api-catalogue#746]
Problem with 'Bank Holidays' (https://www.api.gov.uk/gds/bank-holidays/)

Intermittently receiving this error in Power BI:

Unable to connect to the remote serverDetailsReason = DataSource.Error
Detail = https://www.gov.uk/bank-holidays.json

**Comment by RobNicholsGDS** [comment]
It appears that the application behind that API has been archived. You can still raise an issue on the application's repo:

[ Calendar application issues ](https://github.com/alphagov/calendars/issues)
