### ISSUE TITLE
FHRS Re: 'Food Hygiene Ratings Scheme (FHRS)'

### ISSUE THREAD

**Issue by rababshaikh** [co-cddo/api-catalogue#784]
Problem with 'Food Hygiene Ratings Scheme (FHRS)' (https://www.api.gov.uk/fsa/food-hygiene-ratings-scheme-fhrs/)

**Comment by RobNicholsGDS** [comment]
Could you please describe the problem.

**Comment by RobNicholsGDS** [comment]
I am afraid that with a description of the problem that we are unable to help. The API contact is data@food.gov.uk. I suggest you contact them if there are problems with the operation of that API.
