### ISSUE TITLE
Re: 'GOVUK Notify'

### ISSUE THREAD

**Issue by jabley** [co-cddo/api-catalogue#796]
Problem with 'GOVUK Notify' (https://www.api.gov.uk/dwp/govuk-notify/)

It seems very confusing that DWP have a GOVUK Notify, when [Cabinet Office operate a thing called GOV.UK Notify](https://www.api.gov.uk/gds/gov-uk-notify/#gov-uk-notify).

#712 is perhaps a similar issue, in that DWP are listing an API called GOVUK Pay. Do they perhaps mean that DWP are consumers of the GOV.UK APIs?

**Comment by RobNicholsGDS** [comment]
I am afraid we just maintain the catalogue. If you have a problem with the service listed you will need to contact the owners of that service for a resolution. So I suggest you email integration.technologyplatforms@dwp.gov.uk
