### ISSUE TITLE
Re: 'Tidal API - Premium'

### ISSUE THREAD

**Issue by BudgieWatts** [co-cddo/api-catalogue#797]
Problem with 'Tidal API - Premium' (https://www.api.gov.uk/ukho/tidal-api-premium/)
Problem with 'UK Tidal API - Discovery' (https://www.api.gov.uk/ukho/uk-tidal-api-discovery/)
Problem with 'Tidal API - Foundation' (https://www.api.gov.uk/ukho/tidal-api-foundation/)

The documentation endpoints return a 503

Something like this (https://developer.admiralty.co.uk/api-details#api=uk-tidal-api-foundation) (as one example) might work better.

Cheers :)

**Comment by RobNicholsGDS** [comment]
This PR has fixed that error: https://github.com/co-cddo/api-catalogue/pull/849
