### ISSUE TITLE
Re: 'UK Tidal API - Discovery'

### ISSUE THREAD

**Issue by Cameron999** [co-cddo/api-catalogue#814]
Problem with 'UK Tidal API - Discovery' (https://www.api.gov.uk/ukho/uk-tidal-api-discovery/)

the api documentation link is giving a server 500 error - unavailable.

**Comment by Pearsoj2** [comment]
email here and let them know customerservices@ukho.gov.uk

**Comment by RobNicholsGDS** [comment]
This PR has fixed that error: https://github.com/co-cddo/api-catalogue/pull/849
