### ISSUE TITLE
Re: 'GOV.UK Trade Tariff API'

### ISSUE THREAD

**Issue by Shores123** [co-cddo/api-catalogue#820]
Problem with 'GOV.UK Trade Tariff API' (https://www.api.gov.uk/hmrc/gov-uk-trade-tariff-api/)
This Rest API doesnt appear to work.
I am unable to connect to it. or access the data within it. Is there anyone that can either aid in an alternative, or explain why this may be?

**Comment by RobNicholsGDS** [comment]
You will need to contact trade-tariff-support@transformuk.com for help with the operation of the API. I am afraid we just maintain the catalogue.
