### ISSUE TITLE
Re: 'Ordnance Survey Places API'

### ISSUE THREAD

**Issue by TiannaB1234** [co-cddo/api-catalogue#824]
Problem with 'Ordnance Survey Places API' (https://www.api.gov.uk/nd/ordnance-survey-places-api/)

The information is incorrect - the data is updated up-to-daily

**Comment by RobNicholsGDS** [comment]
I am afraid we just provide the catalogue. You'll need to contact the owners of the API if its operation is not correct. I'd suggest starting here: https://digital.nhs.uk/developer
