### ISSUE TITLE
Re: 'UK Tidal API - Discovery'

### ISSUE THREAD

**Issue by Doug-exe** [co-cddo/api-catalogue#832]
Problem with 'UK Tidal API - Discovery' (https://www.api.gov.uk/ukho/uk-tidal-api-discovery/)
page no longer works - gives error

**Comment by aiddy** [comment]
Same. 

Link to text [UK Tidal API - Discovery documentation](https://admiraltyapi.portal.azure-api.net/docs/services/uk-tidal-api/operations/Stations_GetStation) goes to `https://admiraltyapi.portal.azure-api.net/docs/services/uk-tidal-api/operations/Stations_GetStation` which is giving `HTTP Error 503. The service is unavailable.`

**Comment by RobNicholsGDS** [comment]
This PR has fixed that error: https://github.com/co-cddo/api-catalogue/pull/849

**Comment by aiddy** [comment]
:ty:
