### ISSUE TITLE
Re: 'Business Source Adjustable Summary (MTD)'

### ISSUE THREAD

**Issue by StephenEdginton** [co-cddo/api-catalogue#842]
Problem with 'Business Source Adjustable Summary (MTD)' (https://www.api.gov.uk/hmrc/business-source-adjustable-summary-mtd/)
The api link should drop the version and just point to the root as it is a 404 when you pin it and remove it

**Comment by RobNicholsGDS** [comment]
This issue has been fixed as part of PR https://github.com/co-cddo/api-catalogue/pull/848
