### ISSUE TITLE
Re: 'GOV.UK Courts and Tribunals Publishing API'

### ISSUE THREAD

**Issue by acjolly21** [co-cddo/api-catalogue#855]
Problem with 'GOV.UK Courts and Tribunals Publishing API' (https://www.api.gov.uk/moj/gov-uk-courts-and-tribunals-publishing-api/)

Can you please advise how to get authorisation (API key), etc. in order to access this court information using the APIs.

I cannot find this information in the github.

Thanks,
Tony.

**Comment by RobNicholsGDS** [comment]
Hi, as I commented in [this issue](https://github.com/co-cddo/api-catalogue/issues/864) - it looks like the repository has been archived. So I think the best option is to start with a general enquiry to MoJ.
