### ISSUE TITLE
[EPC and postcode/API key request]

### ISSUE THREAD

**Issue by zeldox258** [co-cddo/api-catalogue#916]
**Please fill in the following information:**

**Base URL:**

**Name:** EPC datas and address datas

**Description:**

**Documentation URL:** `https://content-api.publishing.service.gov.uk/`

**Maintainer:** Huseyin Omer Guray

**Provider:** Government Digital Service

**Area Served:** house searching

**Start Date:** 2024-08-19

**End Date:**2026-08-19

**Alternate Name:** Freetold

**Provider URL:** freetold.com

Hello,

This is a software engineer from London. I am building an app for house rental searching. 

This is the link so far: [freetold.com](http://freetold.com/)

Can I have access to endpoints please? I willl need for address and epc datas. from postcodes.

Best regards

**Comment by RobNicholsGDS** [comment]
@zeldox258 The catalogue is a listing of available APIs. We do not maintain the APIs themselves.

There is a support section of Content API you've linked to. The Support section details how to contact the team managing the system for help: 

  https://content-api.publishing.service.gov.uk/#support
